# Generated by Django 3.2.18 on 2023-03-08 17:25

from django.db import migrations, models
from django_saml2_auth.operations import LockTimeout


class Migration(migrations.Migration):

    dependencies = [
        ("django_saml2_auth", "0001_initial"),
    ]

    operations = [
        LockTimeout(),
        migrations.AddField(
            model_name="samlmetadata",
            name="enable_optional_saml",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="samlmetadata",
            name="enable_saml",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
