# Generated by Django 3.2.20 on 2023-10-09 14:16

from django.db import migrations, models
from django_saml2_auth.operations import LockTimeout


class Migration(migrations.Migration):

    dependencies = [
        ('django_saml2_auth', '0004_alter_samlmetadata_enable_optional_saml'),
    ]

    operations = [
        LockTimeout(),
        migrations.AlterField(
            model_name='samlmetadata',
            name='metadata_contents',
            field=models.TextField(blank=True),
        ),
    ]
