# Generated by Django 3.2.23 on 2023-12-12 17:29

from django.db import migrations, models
import passthrough.operations


class Migration(migrations.Migration):

    dependencies = [
        ('django_saml2_auth', '0005_alter_samlmetadata_metadata_contents'),
    ]

    operations = [
        passthrough.operations.LockTimeout(),
        migrations.AddField(
            model_name='samlmetadata',
            name='host_name',
            field=models.TextField(blank=True, help_text='e.g. test.example.com'),
        ),
    ]
