# Generated by Django 3.2.23 on 2023-12-12 17:29

from django.db import migrations, models
from django_saml2_auth.operations import LockTimeout
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('django_saml2_auth', '0005_alter_samlmetadata_metadata_contents'),
    ]

    operations = [
        linter.IgnoreMigration(),
        LockTimeout(),
        migrations.AddField(
            model_name='samlmetadata',
            name='host_name',
            field=models.TextField(
                null=True,
                blank=True,
                help_text=(
                    "e.g. test.example.com. When populated, only requests coming "
                    "from a specific host will have SAML enabled."
                )
            ),
        ),
        migrations.AlterField(
            model_name='samlmetadata',
            name='email_domain',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name="samlmetadata",
            constraint=models.UniqueConstraint(
                fields=["email_domain", "host_name"],
                name="unique_email_host_name",
            ),
        ),
    ]
