# Generated by Django 4.2.11 on 2024-05-27 13:01

import django.contrib.postgres.fields
from django.db import migrations, models
from django_saml2_auth.operations import LockTimeout


class Migration(migrations.Migration):
    dependencies = [
        ("django_saml2_auth", "0006_samlmetadata_host_name"),
    ]

    operations = [
        LockTimeout(),
        migrations.AddField(
            model_name="samlmetadata",
            name="exempt_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(),
                blank=True,
                help_text="Emails that are exempt from SAML.",
                null=True,
                size=None,
            ),
        ),
    ]
