# Generated by Django 4.2.14 on 2024-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_saml2_auth', '0007_samlmetadata_exempt_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='samlmetadata',
            name='enable_otp',
            field=models.BooleanField(blank=True, default=False, help_text='When True, authenticates the user via the OTP server.', null=True),
        ),
    ]
