# Generated by Django 4.2.14 on 2024-07-15 17:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_saml2_auth', '0008_samlmetadata_enable_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('user_id', models.TextField()),
                ('payload', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='otpusage',
            constraint=models.UniqueConstraint(fields=('token', 'user_id'), name='unique_token_for_user_id'),
        ),
    ]
